osx: &osx
   os: osx
   language: generic
matrix:
   include:
#      - <<: *osx
#        osx_image: xcode6.4
#      - <<: *osx
#        osx_image: xcode7.3
#      - <<: *osx
#        osx_image: xcode8.3
#      - <<: *osx
#        osx_image: xcode9
      - <<: *osx
        osx_image: xcode9.4
#      - <<: *osx
#        osx_image: xcode10.1
#      - <<: *osx
#        osx_image: xcode11

install:
#  - gcc -dM -E -x c /dev/null
#  - g++ -dM -E -x c /dev/null
  - cc -dM -E -x c /dev/null
  - echo 'int fnord () __attribute__((visibility("default"))); int main(){}' | cc -x c -

script:
#  - gcc -dM -E -x c /dev/null
#  - g++ -dM -E -x c /dev/null
  - cc -dM -E -x c /dev/null
  - echo 'int fnord () __attribute__((visibility("default"))); int main(){}' | cc -x c -
